apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gowebapp-deployment
  labels:
    app: gowebapp

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gowebapp
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
        - name: gowebapp-pod
          image: puneethkumarv48/gowebapp:v2
          ports:
            - containerPort: 8080